### ISSUE TITLE
Volunteer entry is cut off

### ISSUE THREAD

**Issue by tu-trinh** [OC-Hackers/Volunteer-App-Client#26]
Hi Voluntu people,

Could you make it so that the approve hours screen shows a board member's activity description completely? Right now it's cut off after a few words and I can't tell what the board member did.

![voluntu bug](https://cloud.githubusercontent.com/assets/22339307/23930669/0647450e-08eb-11e7-96af-dc4fd8818e8f.JPG)

Thanks,
Alina

**Comment by syy1125** [comment]
Hi Alina,
Thank you for bringing this up. We are working to fix this issue now.
Jack Sun

**Comment by JasonILTG** [comment]
Issue has been fixed [here](https://github.com/OC-Hackers/Volunteer-App-Client/commit/a4c5d037a0e95dcab5e8b8c617a9552f9fc18422)
